# based on https://robertohuertas.com/2019/01/20/publish-flutter-package-with-travis/
# and https://itnext.io/configuring-travis-ci-and-coveralls-with-flutter-4c65edfc42d3
language: dart
dart:
  - stable
os:
  - linux
sudo: false
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - echo 'Avoid default Travis CI install step' # this is to avoid an error with pub in Travis
before_script:
  - cd ..
  - git clone https://github.com/flutter/flutter.git
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
script:
  - cd $TRAVIS_BUILD_DIR
  - flutter packages get
  # - flutter analyze --no-pub --no-current-package lib - skipping
  # - flutter test - skipping
  - flutter packages pub publish --dry-run
before_deploy:
  - chmod +x ./.travis/publish.sh # giving execution permissions to this file to avoid error 127.
  - mv ./.travis ../ # moving this out the publication folder as we don't want to publish it.
deploy:
  provider: script
  skip_cleanup: true
  script: '../.travis/publish.sh'
  on:
    tags: true
branches:
  only: [master]
cache:
  directories:
    - $HOME/.pub-cache
